const node = {
  items: [
    {
      title: "Master node",
      values: [
        {
          mode: "browse",
          documentation: "<div class='node' />",
          id: "",
          name: "DS Smith Almelo",
          icon: "icon-plant",
          color: "success",
          colorServant: "danger",
        },
        {
          mode: "browse",
          documentation: "<div class='node has-placeholder' />",
          id: "",
          name: "Plant name",
          icon: "icon-plant",
          color: "success",
          colorServant: "danger",
          class: "has-placeholder",
        },
        {
          mode: "edit",
          documentation: "<div class='node has-placeholder' />",
          id: "3",
          name: "Plant name",
          icon: "icon-plant",
          color: "success",
          colorServant: "danger",
          class: "has-placeholder",
          "add-child": true,
        },
        {
          mode: "edit",
          documentation: "<div class='node is-editable has-placeholder' />",
          id: "4",
          name: "Plant name",
          icon: "icon-plant",
          color: "success",
          colorServant: "danger",
          "add-child": true,
          class: "is-editable has-placeholder",
        },
        {
          mode: "edit",
          documentation: "<div class='node' />",
          id: "1",
          name: "DS Smith Almelo",
          icon: "icon-plant",
          color: "success",
          colorServant: "danger",
          "add-child": true,
        },
        {
          mode: "edit",
          documentation: "<div class='node is-editable' />",
          id: "2",
          name: "DS Smith Almelo",
          icon: "icon-plant",
          color: "success",
          colorServant: "danger",
          "add-child": true,
          class: "is-editable",
        },
        {
          mode: "edit",
          documentation: "<div class='node to-edge' />",
          id: "9",
          name: "Plant name",
          icon: "icon-plant",
          color: "success",
          colorServant: "danger",
          "edgeBig-active": true,
          "edgeSmallTop-active": true,
          "edgeSmallBottom-active": true,
          "edgeSmallLeft-active": true,
          "edgeSmallRight-active": true,
          class: "to-edge",
        },
        {
          mode: "edit",
          documentation: "<div class='node to-edge' />",
          id: "10",
          name: "Plant name",
          icon: "icon-plant",
          color: "success",
          colorServant: "danger",
          "edgeSmallRight-active": true,
          class: "to-edge",
        },
        {
          mode: "edit",
          documentation: "<div class='node to-edge' />",
          id: "11",
          name: "Plant name",
          icon: "icon-plant",
          color: "success",
          colorServant: "danger",
          "edgeSmallTop-active": true,
          class: "to-edge",
        },
      ],
    },
    {
      title: "Servant node",
      values: [
        {
          mode: "browse",
          documentation: "<div class='node' />",
          id: "",
          name: "Tracker ABC",
          icon: "icon-tracker",
          color: "danger",
          "add-child": true,
        },
        {
          mode: "browse",
          documentation: "<div class='node has-placeholder' />",
          id: "",
          name: "Tracker name",
          icon: "icon-tracker",
          color: "danger",
          "add-child": true,
          class: "has-placeholder",
        },
        {
          mode: "edit",
          documentation: "<div class='node has-placeholder' />",
          id: "7",
          name: "Tracker name",
          icon: "icon-tracker",
          color: "danger",
          "add-child": true,
          class: "has-placeholder",
        },
        {
          mode: "edit",
          documentation: "<div class='node is-editable has-placeholder' />",
          id: "8",
          name: "Tracker name",
          icon: "icon-tracker",
          color: "danger",
          "add-child": true,
          class: "is-editable has-placeholder",
        },
        {
          mode: "edit",
          documentation: "<div class='node' />",
          id: "5",
          name: "Tracker name",
          icon: "icon-tracker",
          color: "danger",
          "add-child": true,
        },
        {
          mode: "edit",
          documentation: "<div class='node is-editable' />",
          id: "6",
          name: "Tracker name",
          icon: "icon-tracker",
          color: "danger",
          "add-child": true,
          class: "is-editable",
        },
        {
          mode: "edit",
          documentation: "<div class='node from-edge is-editable' />",
          id: "12",
          name: "Tracker name",
          icon: "icon-tracker",
          color: "danger",
          "edgeSmallLeft-active": true,
          "add-child": true,
          class: "from-edge is-editable",
        },
        {
          mode: "edit",
          documentation: "<div class='node from-edge' />",
          id: "13",
          name: "Tracker name",
          icon: "icon-tracker",
          color: "danger",
          "edgeSmallLeft-active": true,
          class: "from-edge",
        },
        {
          mode: "edit",
          documentation: "<div class='node to-edge' />",
          id: "14",
          name: "Tracker name",
          icon: "icon-tracker",
          color: "danger",
          "edgeSmallBottom-active": true,
          class: "to-edge",
        },
      ],
    },
  ],
};
module.exports = node;
